---
title: Mapas com geobr
output: html_document
author: Mateus Cardoso
date: '2021-03-05'
slug: mapas-com-geobr
categories:
  - R
tags:
  - Mapas
  - geobr
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	fig.keep = "all",
	message = FALSE,
	warning = FALSE
)
```

Blablabla

### Pacotes necessários

```{r, results='hide'}
library(tidyverse)
library(geobr)

sm<-read_municipality(code_muni = 4316907)
escolas<-read_schools()
escolas<-escolas %>% filter(name_muni == "Santa Maria",
                            abbrev_state == "RS")

```


```{r out.width=c('50%', '50%'), fig.show='hold'}

ggplot()+
  geom_sf(data = sm, size=.5)+
  geom_sf(data = escolas)+
  theme_minimal()

ggplot()+
  geom_sf(data = sm, fill="#2D3E50", color="orange", size=.5)+
  geom_sf(data = escolas, color = "orange")+
  theme_minimal()
 
```


### Com leaflet

```{r out.width='100%'}
library(leaflet)
library(tidyverse)

leaflet(escolas) %>% 
  addTiles() %>% 
  addMarkers(popup =
             ~paste("<B>Nome:</B> ", name_school, "<br>",
                    "<B>Dependência Administrativa:</B> ", admin_category, "<br>"),
             label = ~name_school)



```

<br/><br/>
### Unidades de Saúde

```{r, results='hide'}
us<-read_health_facilities()

#código do município com 6 dígitos neste
us<-us %>% filter(code_muni == 431690)
```

```{r, fig.align='center'}
ggplot()+
  geom_sf(data = sm)+
  geom_sf(data = us)+
  theme_minimal()
```
<br/><br/>

```{r out.width='100%'}
leaflet(us)%>% 
  addTiles() %>% 
  addMarkers()
```

<br/><br/>

### Referências

Joe Cheng, Bhaskar Karambelkar and Yihui Xie (2021). leaflet: Create Interactive Web Maps with the JavaScript 'Leaflet' Library. R package version 2.0.4.1. <https://CRAN.R-project.org/package=leaflet>.

Pereira, R.H.M.; Gonçalves, C.N.; et al. (2019) geobr: Loads Shapefiles of Official Spatial Data Sets of Brazil. GitHub repository - <https://github.com/ipeaGIT/geobr>.







