baseURL = "https://lppufsm.com/"
languageCode = "en-us"
title = "Liga de Políticas Públicas UFSM"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "Sobre"
url     = "about"
weight  = 2

[[menu.main]]
name    = "Publicações"
url     = "blog"
weight  = 3

[[menu.main]]
weight  = 4
name    = "Recomendações"
url = "re"
 
[[menu.main]]
name    = "Eventos"
url     = "service"
weight  = 5

[[menu.main]]
name    = "R"
url     = "re"
weight  = 6

[[menu.main]]
name    = "Contato"
url     = "contact"
weight  = 7

# Site Params
[params]
home = "Início"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/ccsh2.jpg"
heading = "LIGA DE POLÍTICAS PÚBLICAS"
description = " A LIGA TAL TAL TAL."
# button
btn     = false
btnText = "QUEM SOMOS"
btnURL  = "https://themefisher.com/"

# flip text
[[params.banner.flipText]]
title   = "UFSM"


# Homepage About Section
[params.about]
enable  = true
title   = "QUEM SOMOS"
content = "Hello, I’m a UI/UX Designer & Front End Developer from Victoria, Australia. I hold a master degree of Web Design from the World University.And scrambled it to make a type specimen book. It has survived not only five centuries. <br> <br> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, adipisci voluptatum repudiandae, natus impedit repellat aut officia illum at assumenda iusto reiciendis placeat. Temporibus, vero."
image   = "images/about/about2.jpeg"

# Call to Action
[params.cta]
enable  = true
title   = "QUER PARTICIPAR?"
content = "O processo seletivo de 2021 está aberto!"
btnText = "Inscreva-se"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = false
title   = "Latest Works"
subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "#"

[[params.socialIcon]]
icon = "ion-social-twitter"
url = "#"

[[params.socialIcon]]
icon = "ion-email"
url = "#"