---
title: Mapas com geobr
output: html_document
author: Mateus Cardoso
date: '2021-03-05'
slug: mapas-com-geobr
categories:
  - R
tags:
  - Mapas
  - geobr
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	results = "hide"
)
```

Blablabla

### Pacotes necessários

```{r}
library(tidyverse)
library(geobr)
library(ggthemes)

sm<-read_municipality(code_muni = 4316907)
escolas<-read_schools()
escolas<-escolas %>% filter(name_muni == "Santa Maria",
                            abbrev_state == "RS")



ggplot()+
  geom_sf(data = sm, fill="#2D3E50", color="#FEBF57", size=.5)+
  geom_sf(data = escolas, color = "orange")+
  theme_minimal()
 
```


### Com leaflet

```{r}
library(leaflet)
library(leaflet.extras)

sm<-read_municipality(code_muni = 4316907)
escolas<-read_schools()
escolas<-escolas %>% filter(name_muni == "Santa Maria",
                            abbrev_state == "RS")

leaflet(escolas) %>% addTiles() %>% addCircles(popup =~paste("<B>Nome:</B> ", name_school, "<br>", "<B>Dependência Administrativa:</B> ", admin_category, "<br>"), label = ~name_school, opacity = 1, weight = 8)


```

```{r}
htmltools::includeHTML("map.html")
```


### Referências

Pereira, R.H.M.; Gonçalves, C.N.; et. all (2019) geobr: Loads Shapefiles of Official Spatial Data Sets of Brazil. GitHub repository - <https://github.com/ipeaGIT/geobr>.





